name: R3
title: Restoring. Rational. Radical.
description: Restoring. Rational. Radical.
keywords: Restoring, Rational, Radical, Missions, Service, Non-profit
domain: r3missions.org

markdown: redcarpet

assets:
  cache: true
  js_compressor: uglifier
  css_compressor: sass
  gzip: false

exclude:
  - Gemfile
  - Gemfile.lock
  - bin
  - vendor
  - bower.json
  - bower_components
